### ISSUE TITLE
Function4: CleverWordCloud

### ISSUE THREAD

**Issue by Vikiano** [UBC-MDS/clevercloudr#2]
Created an empty function and roxygen2 documentation.

**Comment by ajuliettet** [comment]
As discussed in the meeting today. My function CleverLemStem will return a vector of string. It's actually perfect because you can make your input as a vector of string and do df <- data.frame(word)  and group_by(word) |> summarise(count = n()) I think that work with WordCloud 2 in R.

**Comment by Vikiano** [comment]
I have fixed it. Your function's output is my function's input now. Kindly confirm, created a PR.

**Comment by ajuliettet** [comment]
Awesome! I think your function's input variable name doesn't need to be "CleverLemStem_output"..any generic name like "text" will be fine. We don't want people get confused that think that they have to use the output of CleverLemStem() to create the word cloud. They can use any vector of string. Let me know what you think!

**Comment by Vikiano** [comment]
I have just fixed that, changed the input variable name to "text"
