### ISSUE TITLE
Milestone 3 submission

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloudr#44]
Hi, it looks like our work was done. We reviewed the roxygen2, created vignette and also create the usage page using pkgdown. Let's talk about the submission here.

**Comment by adrianne-l** [comment]
The Github Action was setup and passed all the checks after all our latest changes. I think we are good for submission.

**Comment by ajuliettet** [comment]
The issue to R license discussion: https://github.com/UBC-MDS/clevercloudr/issues/44

**Comment by ajuliettet** [comment]
**1. Repo:** 
R: https://github.com/UBC-MDS/clevercloudr

**2. Releases** 
R: https://github.com/UBC-MDS/clevercloudr/releases/tag/v.1.1.0 

**3. Issues on license** 
R: https://github.com/UBC-MDS/clevercloudr/issues/34

**4. R review request:** https://github.com/UBC-MDS/software-review-2022/issues/60

**Comment by Arushi282** [comment]
R review request: [review](https://github.com/UBC-MDS/software-review-2022/issues/60)
