### ISSUE TITLE
Function 2: CleverLemStem

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloudr#5]
Please discuss this function here! Thanks!

**Comment by ajuliettet** [comment]
Since R vector coerce each element into the same data type. To write the function defensively, I think we can do the input as a list (so that we can check the type of each element) and convert it to a vector inside the function to do the operations.

**Comment by adrianne-l** [comment]
Thanks! In that case for CleverStopwords, I would take the string input as a list and output as a list of strings as well.
